config/routes.rb
Rails.application.routes.draw do
  resources :avatars
  get 'regenerate', as: :avatars_regenerate, to: "avatars#regenerate"
  root 'avatars#index'

end

app/models/avatar.rb
class Avatar < ActiveRecord::Base
  before_save :check_image

  def check_image
    unless generated
      self.image_location = AvatarGenerator.from_seed(rand(12345..67890))
      self.generated = true
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/avatars_controller.rb
require_relative '../utilities/avatar_generator'
class AvatarsController < ApplicationController
  before_action :set_avatar, only: [:show, :edit, :update, :destroy]

  # GET /avatars
  # GET /avatars.json
  def index
    @avatars = Avatar.all
  end

  # GET /avatars/1
  # GET /avatars/1.json
  def show
  end

  # GET /avatars/new
  def new
    @avatar = Avatar.new
  end

  # GET /avatars/1/edit
  def edit
  end

  # POST /avatars
  # POST /avatars.json
  def create
    @avatar = Avatar.new(avatar_params)
  
    respond_to do |format|
      if @avatar.save
        format.html { redirect_to @avatar, notice: 'Avatar was successfully created.' }
        format.json { render :show, status: :created, location: @avatar }
      else
        format.html { render :new }
        format.json { render json: @avatar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /avatars/1
  # PATCH/PUT /avatars/1.json
  def update
    respond_to do |format|
      if @avatar.update(avatar_params)
        format.html { redirect_to @avatar, notice: 'Avatar was successfully updated.' }
        format.json { render :show, status: :ok, location: @avatar }
      else
        format.html { render :edit }
        format.json { render json: @avatar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /avatars/1
  # DELETE /avatars/1.json
  def destroy
    @avatar.destroy
    respond_to do |format|
      format.html { redirect_to avatars_url, notice: 'Avatar was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def regenerate
    Avatar.all.each do |avatar|
      avatar.generated = false
      avatar.save
    end
    redirect_to avatars_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_avatar
      @avatar = Avatar.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def avatar_params
      params.require(:avatar).permit(:user_id, :generated, :image_location)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/views/avatars/_form.html.erb
<%= form_for(@avatar) do |f| %>
  <% if @avatar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@avatar.errors.count, "error") %> prohibited this avatar from being saved:</h2>

      <ul>
      <% @avatar.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :generated %><br>
    <%= f.check_box :generated %>
  </div>
  <div class="field">
    <%= f.label :image_location %><br>
    <%= f.text_field :image_location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/avatars/edit.html.erb
<h1>Editing Avatar</h1>

<%= render 'form' %>

<%= link_to 'Show', @avatar %> |
<%= link_to 'Back', avatars_path %>

app/views/avatars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Avatars</h1>

<table>
  <thead>
    <tr> <%= link_to "Re-Generate All", avatars_regenerate_path %></tr>
    <tr>
      <th>User</th>
      <th>Generated</th>
      <th>Image location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @avatars.each do |avatar| %>
      <tr>
        <td><%= image_tag avatar.image_location, size: "150x150" if avatar.generated %></td>
        <td><%= avatar.user_id %></td>
        <td><%= avatar.generated %></td>
        <td><%= avatar.image_location %></td>
        <td><%= link_to 'Show', avatar %></td>
        <td><%= link_to 'Edit', edit_avatar_path(avatar) %></td>
        <td><%= link_to 'Destroy', avatar, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Avatar', new_avatar_path %>

app/views/avatars/new.html.erb
<h1>New Avatar</h1>

<%= render 'form' %>

<%= link_to 'Back', avatars_path %>

app/views/avatars/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag @avatar.image_location, size:"50x50" if @avatar.generated %>

<p>
  <strong>User:</strong>
  <%= @avatar.user_id %>
</p>

<p>
  <strong>Generated:</strong>
  <%= @avatar.generated %>
</p>

<p>
  <strong>Image location:</strong>
  <%= @avatar.image_location %>
</p>

<%= link_to 'Edit', edit_avatar_path(@avatar) %> |
<%= link_to 'Back', avatars_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SnagleGenerator</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>